# Generated by Django 4.0.2 on 2022-02-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('Company_name', models.CharField(max_length=150)),
                ('Location', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=100)),
                ('Company_detail', models.TextField()),
                ('Phone', models.CharField(max_length=13)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
    ]
