# Generated by Django 4.0.2 on 2022-02-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_company_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('Name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('Relation', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('Phone', models.CharField(max_length=13)),
            ],
        ),
    ]
